### ISSUE TITLE
Erorr: The editor has encountered an unexpected error.

### ISSUE THREAD

**Issue by JQOz** [marcusig/gutenberg-section-block#14] opened 2019-01-13 19:08 UTC
Hi ,

i get this error:

The editor has encountered an unexpected error.

![bildschirmfoto 2019-01-13 um 20 07 37](https://user-images.githubusercontent.com/19261428/51089517-e78b0580-176e-11e9-8995-854d232336f7.png)

**Comment by AtlasianOnline** [comment] 2019-01-13 19:35
if i use this plugin with another Gutenberg add-on (GhostKit) i get this error.

What is the reason for this?

**Comment by marcusjwilson** [comment] 2019-02-05 13:00
I am experiencing the same issue as @JQOz in WP 5.0.3.

Is there a quick fix?

**Comment by ghost** [comment] 2019-02-25 02:30
Same issue with ghostkit enabled. It happens when the "Background Image" accordion item in the section block sidebar is clicked. Looks like its related to issue #13 

Here is the error from the gutenberg editor:

```_createModes/<@http://rclaw.local:8888/wp-includes/js/media-views.min.js?ver=5.1:1:24786
arrayEach@webpack-internal:///13:516:11
forEach@webpack-internal:///13:9344:14
_createModes@http://rclaw.local:8888/wp-includes/js/media-views.min.js?ver=5.1:1:24749
initialize@http://rclaw.local:8888/wp-includes/js/media-views.min.js?ver=5.1:1:24155
initialize@http://rclaw.local:8888/wp-includes/js/media-views.min.js?ver=5.1:1:25775
initialize@http://rclaw.local:8888/wp-includes/js/media-views.min.js?ver=5.1:1:28647
b.View@http://rclaw.local:8888/wp-includes/js/backbone.min.js?ver=1.2.3:1:14121
constructor@http://rclaw.local:8888/wp-includes/js/wp-backbone.min.js?ver=5.1:1:2602
constructor@http://rclaw.local:8888/wp-includes/js/media-views.min.js?ver=5.1:1:23590
N/d<@http://rclaw.local:8888/wp-includes/js/backbone.min.js?ver=1.2.3:1:22091
N/d<@http://rclaw.local:8888/wp-includes/js/backbone.min.js?ver=1.2.3:1:22091
N/d<@http://rclaw.local:8888/wp-includes/js/backbone.min.js?ver=1.2.3:1:22091
23/wp.media@http://rclaw.local:8888/wp-includes/js/media-models.min.js?ver=5.1:1:1153
t@http://rclaw.local:8888/wp-includes/js/dist/edit-post.min.js?ver=3.1.11:12:6515
zf@http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:69:258
Mf@http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:87:4
ph@http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:98:474
eg@http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:125:307
fg@http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:126:168
wc@http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:138:237
fa@http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:137:115
ng@http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:149:69
Se@http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:40:45
```

Here is the error from the javascript console:
```TypeError: "this.activateMode is not a function"
	_createModes media-views.min.js:1
arrayEach2Lodash	_createModes media-views.min.js:1
	initialize media-views.min.js:1
	initialize media-views.min.js:1
	initialize media-views.min.js:1
View2Backbone	constructor media-views.min.js:1
d3Backbone	media media-models.min.js:1
	t edit-post.min.js:12
	zf react-dom.min.js:69
	Mf react-dom.min.js:87
	ph react-dom.min.js:98
	eg react-dom.min.js:125
	fg react-dom.min.js:126
	wc react-dom.min.js:138
	fa react-dom.min.js:137
	ng react-dom.min.js:149
	Se react-dom.min.js:40
 react-dom.min.js:104:245
	Pf http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:104
	callback http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:113
	uf http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:65
	tf http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:65
	zc http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:146
	wc http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:138
	fa http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:137
	ng http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:149
	Se http://rclaw.local:8888/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:40
```

**Comment by marcusig** [comment] 2019-02-25 07:24
This is a duplicate of https://github.com/marcusig/gutenberg-section-block/issues/13 

It should be fixed in the latest version.

**Closed as completed by marcusig** 2019-02-25 07:24 UTC
